# Function to create plots of cumulative means generated by fun_diagnostics

fun_diagnostics_plots <- function(results_combined){ 
  
  #===============================================================================
  # Cumulative Means
  #===============================================================================
  
  # For our combined results, we create an array to store the cumulative means
  # Row 1: Outcomes of simulation/patient 1
  # Row 2: Mean outcomes of simulations/patients 1 and 2
  # Row 3: Mean outcomes of simulations/patients 1 - 3
  # ...
  # Row 1'000: Mean outcomes of simulations/patients 1 - 1'000
  # Etc.
  
  cumulative_mean <- array(0,
                           dim=c(nrow(results_combined),ncol(results_combined)),
                           dimnames = list(c(1:nrow(results_combined)),
                                           names(results_combined)))
  
  for (i in 1:ncol(results_combined)) {
    cumulative_mean[,i] <- cumsum(results_combined[,i]) / seq_along(results_combined[,i])
  }
  
  # Convert cumulative means into data frame
  
  cumulative_mean <- data.frame(cumulative_mean)
  
  #===============================================================================
  # Plots
  #===============================================================================
  
  colNames <- names(cumulative_mean)
  
  cumulative_mean_plots <- vector('list', length(colNames))
  
  for (i in seq_along(cumulative_mean)) {
    message(i)
    cumulative_mean_plots[[i]] <- local({
      i <- i
      
      p1 <- ggplot(data = cumulative_mean, aes_string(x = 1:nrow(cumulative_mean), y = cumulative_mean[,colNames[i]])) +
        geom_line() +
        xlab(names(cumulative_mean)[i]) +
        ylab("Value") + 
        settings$ggplot_theme
      
      print(p1)
    })
  }
  
  return(cumulative_mean_plots)
  
  
}


