#' Function to analyze microsimulation data with multi-arm causal forest (MACF)
#' and determine optimal treatment assignment based on policy tree
#' Input: 
#' 1. Requires a decision rule model structure generated by fun_opt_treat
#' 2. Number of trees in causal forest
#' 3. Honesty of causal forest
#' 4. Seed for causal forest
#' 5. Percentage of sample used to train policy tree
#' 6. Whether or not to do hybrid with additional layer of depth (3 instead of 2)

fun_MACF <- function(dec_rules, num.trees, honesty, seed, policysample, hybrid){ 
  
  #===============================================================================
  # Causal Forest
  #===============================================================================
  
  # garbage collection to keep memory free
  gc()
  
  # empty list
  dec_rules$MACF <- list()
  
  # Log start time
  dec_rules$MACF$time$start <- Sys.time()
  
  # Generate treatment propensities. By definition, we know every patient has 
  # completely random treatment propensities, meaning they should be the same
  # for all treatments
  
  dec_rules$MACF$W_hat <- matrix(data = 1/dec_rules$ntreat,
                            nrow = dec_rules$n,
                            ncol = dec_rules$ntreat)
  
  # Run the multi-arm causal forest
  dec_rules$MACF$mc_forest <- multi_arm_causal_forest(X = dec_rules$X, 
                                                 Y = dec_rules$Y, 
                                                 W = dec_rules$W,
                                                 W.hat = dec_rules$W_hat,
                                                 num.trees = num.trees,
                                                 honesty = honesty,
                                                 seed = seed,
                                                 min.node.size = dec_rules$n/1000)
  
  #Compute doubly robust reward estimates.
  dec_rules$MACF$Gamma.matrix <- double_robust_scores(dec_rules$MACF$mc_forest)
  
  #===============================================================================
  # Policy Tree
  #===============================================================================
  
  # If policysample == 1, we use full sample to train policy tree,
  # If less than 1, then only percentage of sample
  if (policysample == 1) {
    
    train <- 1:(dec_rules$n)
    
  } else {
    
    train <- sample(1:(dec_rules$n), policysample * dec_rules$n)
    
  }
  
  # Fit a depth 2 tree
  dec_rules$MACF$policy_tree <- policy_tree(dec_rules$X[train,], 
                                            dec_rules$MACF$Gamma.matrix[train,], 
                                            depth = 2)
  
  # We predict which treatments patients should receive based on the policy rule
  predicted <- predict(dec_rules$MACF$policy_tree, dec_rules$X)
  
  # We reduce the patients back to the original number, before multiplication for the Causal Forest
  predicted <- predicted[1:nrow(dec_rules$PRC)]
  
  # For each patient we re-code the treatment number back into a name
  for (i in 1:dec_rules$ntreat) {
    
    # Which patients should receive treatment i?
    predict_treat <- which(predicted == i)
    
    if (length(predict_treat) > 0) {
      
      dec_rules[["patient_NMB"]][predict_treat,"POLICY_TREE"]  <- dec_rules[["PRC"]][predict_treat, paste0(dec_rules$MACF$policy_tree$action.names[i],"_NMB")]
      dec_rules[["patient_QALY"]][predict_treat,"POLICY_TREE"]  <- dec_rules[["PRC"]][predict_treat, paste0(dec_rules$MACF$policy_tree$action.names[i],"_QALYs_disc")]
      dec_rules[["patient_COST"]][predict_treat,"POLICY_TREE"]  <- dec_rules[["PRC"]][predict_treat, paste0(dec_rules$MACF$policy_tree$action.names[i],"_cost_disc")]
      
      predicted[predict_treat] <- dec_rules$MACF$policy_tree$action.names[i]
      
    }
  }
  
  # Save the predicted treatments as strings
  dec_rules$MACF$policy_tree_rule <- predicted
  
  #===============================================================================
  # Comparison Table
  #===============================================================================
  # Add row to comparison table
  
  dec_rules$MACF$mean_outcomes <- setNames(data.frame(matrix(data = 0,
                                                             nrow = 1,
                                                             ncol = 3)),
                                           c("QALYs", "Costs", "NMB"))
  
  rownames(dec_rules$MACF$mean_outcomes) <- "POLICY_TREE"
  
  dec_rules$MACF$mean_outcomes[1,"QALYs"] <- mean(dec_rules[["patient_QALY"]][["POLICY_TREE"]])
  dec_rules$MACF$mean_outcomes[1,"Costs"] <- mean(dec_rules[["patient_COST"]][["POLICY_TREE"]])
  dec_rules$MACF$mean_outcomes[1,"NMB"]   <- mean(dec_rules[["patient_NMB"]][["POLICY_TREE"]])
  
  dec_rules$comp_table <- rbind (dec_rules$comp_table, dec_rules$MACF$mean_outcomes)
  
    #===============================================================================
    # Hybrid Policy Tree
    #===============================================================================
    
  if (hybrid == TRUE) {
   
    # garbage collection to keep memory free
    gc()
    
    dec_rules$HMACF <- list()
    
    # Fit a depth 3 tree
    dec_rules$HMACF$policy_tree <- hybrid_policy_tree(dec_rules$X[train,], 
                                                      dec_rules$MACF$Gamma.matrix[train,],
                                                      depth = 3,
                                                      search.depth = 2)
            
    # We predict which treatments patients should receive based on the policy rule
    predicted <- predict(dec_rules$HMACF$policy_tree, dec_rules$X)
    
    # We reduce the patients back to the original number, before multiplication for the Causal Forest
    predicted <- predicted[1:nrow(dec_rules$PRC)]
    
    # For each patient we re-code the treatment number back into a name
    for (i in 1:dec_rules$ntreat) {
      
      # Which patients should receive treatment i?
      predict_treat <- which(predicted == i)
      
      if (length(predict_treat) > 0) {
        dec_rules[["patient_NMB"]][predict_treat,"HYBRID_POLICY_TREE"]  <- dec_rules[["PRC"]][predict_treat, paste0(dec_rules$HMACF$policy_tree$action.names[i],"_NMB")]
        dec_rules[["patient_QALY"]][predict_treat,"HYBRID_POLICY_TREE"]  <- dec_rules[["PRC"]][predict_treat, paste0(dec_rules$HMACF$policy_tree$action.names[i],"_QALYs_disc")]
        dec_rules[["patient_COST"]][predict_treat,"HYBRID_POLICY_TREE"]  <- dec_rules[["PRC"]][predict_treat, paste0(dec_rules$HMACF$policy_tree$action.names[i],"_cost_disc")]
        
        predicted[predict_treat] <- dec_rules$MACF$policy_tree$action.names[i]
        
      }
    }
    
    # Save the predicted treatments as strings
    dec_rules$HMACF$policy_tree_rule <- predicted
    
    #===============================================================================
    # Comparison Table
    #===============================================================================
    # Add row to comparison table
    
    dec_rules$HMACF$mean_outcomes <- setNames(data.frame(matrix(data = 0,
                                                               nrow = 1,
                                                               ncol = 3)),
                                             c("QALYs", "Costs", "NMB"))
    
    rownames(dec_rules$HMACF$mean_outcomes) <- "HYBRID_POLICY_TREE"
    
    dec_rules$HMACF$mean_outcomes[1,"QALYs"] <- mean(dec_rules[["patient_QALY"]][["HYBRID_POLICY_TREE"]])
    dec_rules$HMACF$mean_outcomes[1,"Costs"] <- mean(dec_rules[["patient_COST"]][["HYBRID_POLICY_TREE"]])
    dec_rules$HMACF$mean_outcomes[1,"NMB"]   <- mean(dec_rules[["patient_NMB"]][["HYBRID_POLICY_TREE"]])
    
    dec_rules$comp_table <- rbind (dec_rules$comp_table, dec_rules$HMACF$mean_outcomes)
    
  }
  
  #===============================================================================
  # End
  #===============================================================================
  
  # Log end time
  dec_rules$MACF$time$end <- Sys.time()
  
  # Calculate runtime in seconds
  dec_rules$MACF$time$duration <- as.numeric(dec_rules$MACF$time$end, units = "secs") - as.numeric(dec_rules$MACF$time$start, units = "secs")
  
  # Return list with output
  return(dec_rules)

}
