#' Function to analyze microsimulation data with LASSO regression
#' and determine optimal treatment assignment based on this regression
#' Input: 
#' 1. Requires a decision rule model structure generated by fun_opt_treat
#'

fun_LASSO <- function(dec_rules){ 
  
  # garbage collection to keep memory free
  gc()
  
  #===============================================================================
  # Create data frame
  #===============================================================================
  
  # Create separate covariate table for LASSO
  dec_rules$LASSO$X <- data.frame(dec_rules$X)
  
  # Log start time
  dec_rules$LASSO$time$start <- Sys.time()
  
  ## Add treatment dummies
  for (i in 1:dec_rules$ntreat) {
    dec_rules$LASSO$X[,paste0(levels(dec_rules[["W"]])[[i]])] <- dummy_cols(dec_rules$W)[,i+1]
  }
  
  ## Interact all covariates with each other
  # Number of pairwise interactions
  num_cov          <- length(dec_rules$covariates)
  num_interactions <- choose(num_cov, 2)
  
  # Create a matrix to store results
  interactions <- matrix(NA, nrow = num_interactions, ncol = 3)
  colnames(interactions) <- c("Var1", "Var2", "Interaction")
  
  # Initialize a counter
  counter <- 1
  
  # Loop through all pairs
  for (i in 1:(num_cov - 1)) {
    for (j in (i + 1):num_cov) {
      
      var1   <- paste0(dec_rules$covariates[i]) 
      var2   <- paste0(dec_rules$covariates[j]) 
      varint <- paste0(var1, "_INT_", var2)
      
      dec_rules$LASSO$X[,paste0(varint)] <- dec_rules$LASSO$X[,paste0(var1)] * dec_rules$LASSO$X[,paste0(var2)]
      
    }
  }
  
  # Remove first treatment dummy from data again
  drop <- paste0(levels(dec_rules[["W"]])[[1]])
  dec_rules$LASSO$X = dec_rules$LASSO$X[,!(names(dec_rules$LASSO$X) %in% drop)]
  
  ## Add interactions between treatments and covariates
  for (i in 2:dec_rules$ntreat) {
    
    var1 <- levels(dec_rules[["W"]])[[i]]
    
    for (j in 1:num_cov) {
      
      var2   <- paste0(dec_rules$covariates[j]) 
      varint <- paste0(var1, "_INT_", var2)
      
      dec_rules$LASSO$X[,paste0(varint)] <- dec_rules$LASSO$X[,paste0(var1)] * dec_rules$LASSO$X[,paste0(var2)]
      
    }
  }
  
  ## Add polynomials for continuous patient characteristics
  
  # Determine how many polynomials we want to assess for our covariates
  poly <- 5
  
  for (i in 1:length(dec_rules$covariates)){
    
    # Check if covariate is a dummy. Dummies don't need polynomials
    not_dummy <- any(dec_rules[["X"]][,dec_rules$covariates[i]] != 0 & dec_rules[["X"]][,dec_rules$covariates[i]] != 1)
    
    if (not_dummy) {
      for (j in 2:poly) {
        dec_rules$LASSO$X[,paste0(dec_rules$covariates[i], "_power", j)] <- dec_rules$LASSO$X[,paste0(dec_rules$covariates[i])]^j
        
        # Also interact treatments with polynomials
        for (k in 2:dec_rules$ntreat) {
          
          var1   <- levels(dec_rules[["W"]])[[k]]
          var2   <- paste0(dec_rules$covariates[i], "_power", j)
          varint <- paste0(var1, "_INT_", var2)
          
          dec_rules$LASSO$X[,paste0(varint)] <- dec_rules$LASSO$X[,paste0(var1)] * dec_rules$LASSO$X[,paste0(var2)]
          
        }
      }
    }
  }
  
  #===============================================================================
  # Select model and run regression
  #===============================================================================
  
  # Test LASSO model
  cv_model <- cv.glmnet(x = as.matrix(dec_rules$LASSO$X), 
                        y = dec_rules$Y, 
                        alpha = 1)
  
  # Select covariates based on best lambda
  sel <- coef(cv_model, s = "lambda.min")
  sel_cov <- vector()
  
  for (i in 2:nrow(sel)) {
    if (sel[i] != 0) {
      
      sel_cov <- c(sel_cov,sel@Dimnames[[1]][i])
      
    }
  }
  
  # Run linear regression with LASSO
  dec_rules$LASSO$X_final <- dec_rules$LASSO$X[,sel_cov]
  
  dec_rules$LASSO$model <- lm(dec_rules$Y ~ ., data = dec_rules$LASSO$X_final)
  
  #===============================================================================
  # Analyze LASSO output
  #===============================================================================
  
  # Determine which treatment is optimal based on regression
  dec_rules$LASSO$LASSO_rule <- vector(length = nrow(dec_rules$PRC))
  
  for (i in 1:nrow(dec_rules$PRC)) {
    
    # Compare the same individual's outcome for each of the different treatments
    predict <- vector(length = dec_rules$ntreat)
    
    for (j in 1:dec_rules$ntreat) {
      predict[j] <- dec_rules$LASSO$model$fitted.values [i + (j-1) * nrow(dec_rules$PRC)]
    }
    
    # Which treatment maximizes the outcome?
    max <- which(predict == max(predict))
    dec_rules$LASSO$LASSO_rule[i] <- levels(dec_rules$W)[max]
    
  }
  
  # See what QALYs, costs, and NMB result out of treatment assignment via LASSO
  for (i in 1:dec_rules$ntreat) {
    
    # Which patients should receive treatment i?
    predict_treat <- which(dec_rules$LASSO$LASSO_rule == levels(dec_rules$W)[i])
    
    if (length(predict_treat) > 0) {
      
      dec_rules[["patient_NMB"]][predict_treat,"LASSO"]  <- dec_rules[["PRC"]][predict_treat, paste0(levels(dec_rules$W)[i],"_NMB")]
      dec_rules[["patient_QALY"]][predict_treat,"LASSO"]  <- dec_rules[["PRC"]][predict_treat, paste0(levels(dec_rules$W)[i],"_QALYs_disc")]
      dec_rules[["patient_COST"]][predict_treat,"LASSO"]  <- dec_rules[["PRC"]][predict_treat, paste0(levels(dec_rules$W)[i],"_cost_disc")]
      
    }
  }
  
  # Mean outcomes based on LASSO treatment assignment
  dec_rules$LASSO$mean_outcomes <- setNames(data.frame(matrix(data = 0,
                                                              nrow = 1,
                                                              ncol = 3)),
                                            c("QALYs", "Costs", "NMB"))
  
  rownames(dec_rules$LASSO$mean_outcomes) <- "LASSO"
  
  dec_rules$LASSO$mean_outcomes[1,"QALYs"] <- mean(dec_rules[["patient_QALY"]][["LASSO"]])
  dec_rules$LASSO$mean_outcomes[1,"Costs"] <- mean(dec_rules[["patient_COST"]][["LASSO"]])
  dec_rules$LASSO$mean_outcomes[1,"NMB"]   <- mean(dec_rules[["patient_NMB"]][["LASSO"]])
  
  # Compare with other treatment strategies
  dec_rules$comp_table <- rbind (dec_rules$comp_table, dec_rules$LASSO$mean_outcomes)
  
  #===============================================================================
  # End
  #===============================================================================
  
  # Log end time
  dec_rules$LASSO$time$end <- Sys.time()
  
  # Calculate runtime in seconds
  dec_rules$LASSO$time$duration <- as.numeric(dec_rules$LASSO$time$end, units = "secs") - as.numeric(dec_rules$LASSO$time$start, units = "secs")
  
  # Return list with output
  return(dec_rules)

}
