#' Function to analyze microsimulation data with a policy tree
#' Input: 
#' 1. Requires a decision rule model structure generated by fun_opt_treat
#' 2. Whether or not to do hybrid with additional layer of depth
#' 3. If hybrid, how many layers deep should the tree go

fun_policy_tree <- function(dec_rules, hybrid, pt_depth){ 
  
  #===============================================================================
  # Start
  #===============================================================================
  
  # garbage collection to keep memory free
  gc()
  
  # empty list
  dec_rules$PT <- list()
  
  # Log start time
  dec_rules$PT$time$start <- Sys.time()
  
  #===============================================================================
  # Prepare data
  #===============================================================================
  
  gamma_matrix <- matrix(0,
                         nrow = dec_rules$n/dec_rules$ntreat,
                         ncol = dec_rules$ntreat)
  
  colnames(gamma_matrix) <- levels(dec_rules$W)
  
  for (i in 1:dec_rules$ntreat) {
    
    n     <- dec_rules$n/dec_rules$ntreat
    start <- 1 + (i-1) * n
    end   <- i * n
    
    gamma_matrix[,i] <- dec_rules$Y[start:end]
    
  }
  
  X <- dec_rules$X[1:(dec_rules$n/dec_rules$ntreat),]
  
  #===============================================================================
  # Policy Tree
  #===============================================================================
  
  # Fit a depth 2 tree
  if (hybrid == FALSE) {
    dec_rules$PT$policy_tree <- policy_tree(X, 
                                            gamma_matrix, 
                                            depth = 2)
  } else if (hybrid == TRUE) {
  # Fit a depth 3 tree
    dec_rules$PT$policy_tree <- hybrid_policy_tree(X, 
                                                   gamma_matrix,
                                                   depth = pt_depth,
                                                   search.depth = 2)
  }

  # We predict which treatments patients should receive based on the policy rule
  predicted <- predict(dec_rules$PT$policy_tree, X)
  
  # For each patient we re-code the treatment number back into a name
  for (i in 1:dec_rules$ntreat) {
    
    # Which patients should receive treatment i?
    predict_treat <- which(predicted == i)
    
    if (length(predict_treat) > 0) {
      
      dec_rules[["patient_NMB"]][predict_treat,"POLICY_TREE"]  <- dec_rules[["PRC"]][predict_treat, paste0(dec_rules$PT$policy_tree$action.names[i],"_NMB")]
      dec_rules[["patient_QALY"]][predict_treat,"POLICY_TREE"]  <- dec_rules[["PRC"]][predict_treat, paste0(dec_rules$PT$policy_tree$action.names[i],"_QALYs_disc")]
      dec_rules[["patient_COST"]][predict_treat,"POLICY_TREE"]  <- dec_rules[["PRC"]][predict_treat, paste0(dec_rules$PT$policy_tree$action.names[i],"_cost_disc")]
      
      predicted[predict_treat] <- dec_rules$PT$policy_tree$action.names[i]
      
    }
  }
  
  # Save the predicted treatments as strings
  dec_rules$PT$policy_tree_rule <- predicted
  
  #===============================================================================
  # Comparison Table
  #===============================================================================
  # Add row to comparison table
  
  dec_rules$PT$mean_outcomes <- setNames(data.frame(matrix(data = 0,
                                                             nrow = 1,
                                                             ncol = 3)),
                                           c("QALYs", "Costs", "NMB"))
  
  rownames(dec_rules$PT$mean_outcomes) <- "POLICY_TREE"
  
  dec_rules$PT$mean_outcomes[1,"QALYs"] <- mean(dec_rules[["patient_QALY"]][["POLICY_TREE"]])
  dec_rules$PT$mean_outcomes[1,"Costs"] <- mean(dec_rules[["patient_COST"]][["POLICY_TREE"]])
  dec_rules$PT$mean_outcomes[1,"NMB"]   <- mean(dec_rules[["patient_NMB"]][["POLICY_TREE"]])
  
  dec_rules$comp_table <- rbind (dec_rules$comp_table, dec_rules$PT$mean_outcomes)
  
  #===============================================================================
  # End
  #===============================================================================
  
  # Log end time
  dec_rules$PT$time$end <- Sys.time()
  
  # Calculate runtime in seconds
  dec_rules$PT$time$duration <- as.numeric(dec_rules$PT$time$end, units = "secs") - as.numeric(dec_rules$PT$time$start, units = "secs")
  
  # Return list with output
  return(dec_rules)

}
